apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: service-label-value
  name: service-name-loadbalancer
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: service-port-name
      port: 8888
      targetPort: 80
      protocol: TCP
  selector:
    deployment-label-key: deployment-label-value
